package ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cantante;
<<<<<<< Upstream, based on origin/master

=======
>>>>>>> d4cbfc7 Merge origin/master
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cantante;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaCrearCantante extends javax.swing.JInternalFrame {
    private ControladorCantante controladorCantante;
    /**
     * Creates new form VentanaCrearPersona
     */
    public VentanaCrearCantante(ControladorCantante controladorCantante) {
        
        initComponents();
        this.controladorCantante = controladorCantante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCantante = new javax.swing.JPanel();
        lblFechaNacimientoCrearPersona = new javax.swing.JLabel();
        lblNombreCrearPersona = new javax.swing.JLabel();
        txtCodigoCantante = new javax.swing.JTextField();
        txtNombreCantante = new javax.swing.JTextField();
        btnAceptarCantante = new javax.swing.JButton();
        btnCancelarCantante = new javax.swing.JButton();
        lblcantantaFondo = new javax.swing.JLabel();
        lblicono = new javax.swing.JLabel();
        lblCantante = new javax.swing.JLabel();
        lblNombreCrearPersona1 = new javax.swing.JLabel();
        lblNombreCrearPersona2 = new javax.swing.JLabel();
        lblNombreCrearPersona3 = new javax.swing.JLabel();
        lblNombreCrearPersona4 = new javax.swing.JLabel();
        lblNombreCrearPersona6 = new javax.swing.JLabel();
        lblNombreCrearPersona7 = new javax.swing.JLabel();
        lblNombreCrearPersona8 = new javax.swing.JLabel();
        lblNombreCrearPersona9 = new javax.swing.JLabel();
        txtNomArtisticoCantante = new javax.swing.JTextField();
        txtApellidoCantante = new javax.swing.JTextField();
        txtEdadCantante = new javax.swing.JTextField();
        txtNacionalidadCantante = new javax.swing.JTextField();
        txtGeneroMusicalCantante = new javax.swing.JTextField();
        txtNumSencillosCantante = new javax.swing.JTextField();
        txtNumConciertosCantante = new javax.swing.JTextField();
        txtNumGirasCantante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblNombreCrearPersona10 = new javax.swing.JLabel();
        txtSalarioCantante = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Datos Crear Cantante"));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelCantante.setBackground(new java.awt.Color(255, 255, 255));
        panelCantante.setToolTipText("Crear Nueva Persona");
        panelCantante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaNacimientoCrearPersona.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblFechaNacimientoCrearPersona.setText("Apellido:");
        panelCantante.add(lblFechaNacimientoCrearPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        lblNombreCrearPersona.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona.setText("Num. Giras:");
        panelCantante.add(lblNombreCrearPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 180, 30));

        txtCodigoCantante.setToolTipText("Ingrese el codigo del cantante");
        txtCodigoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtCodigoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 220, 30));

<<<<<<< Upstream, based on origin/master
=======
        txtDiscografiaCantante.setToolTipText("");
        txtDiscografiaCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscografiaCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtDiscografiaCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 220, 30));

>>>>>>> d4cbfc7 Merge origin/master
        txtNombreCantante.setToolTipText("Ingrese el nombre del cantante");
        txtNombreCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNombreCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 220, 30));

        btnAceptarCantante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAceptarCantante.setText("Aceptar");
        btnAceptarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(btnAceptarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 106, 32));

        btnCancelarCantante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelarCantante.setText("Cancelar");
        btnCancelarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(btnCancelarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 104, 32));

<<<<<<< Upstream, based on origin/master
        lblicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/practica_05_ssuquilanda_jabad/vista/cantante/silue h.png"))); // NOI18N
        panelCantante.add(lblicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 230, 500));
=======
        lblcantantaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/silue h.png"))); // NOI18N
        lblcantantaFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblcantantaFondo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelCantante.add(lblcantantaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 340, 650));
>>>>>>> d4cbfc7 Merge origin/master

        lblicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpeg"))); // NOI18N
        panelCantante.add(lblicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 270, 530));

        lblCantante.setFont(new java.awt.Font("AkayaTelivigala", 1, 36)); // NOI18N
        lblCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1-3.png"))); // NOI18N
        lblCantante.setText("UPS Musik");
        lblCantante.setPreferredSize(new java.awt.Dimension(200, 400));
        panelCantante.add(lblCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 370, 50));

        lblNombreCrearPersona1.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblNombreCrearPersona1.setText("Nombre:");
        panelCantante.add(lblNombreCrearPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        lblNombreCrearPersona2.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona2.setText("Codigo:");
        panelCantante.add(lblNombreCrearPersona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 30));

        lblNombreCrearPersona3.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona3.setText("Edad:");
        panelCantante.add(lblNombreCrearPersona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 78, 30));

        lblNombreCrearPersona4.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona4.setText("Nacionalidad:");
        panelCantante.add(lblNombreCrearPersona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, 30));

<<<<<<< Upstream, based on origin/master
=======
        lblDiscografiaCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblDiscografiaCantante.setText("Discografia:");
        panelCantante.add(lblDiscografiaCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 160, 30));

>>>>>>> d4cbfc7 Merge origin/master
        lblNombreCrearPersona6.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona6.setText("Nombre Artistico:");
        panelCantante.add(lblNombreCrearPersona6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 210, 30));

        lblNombreCrearPersona7.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona7.setText("Genero Musical:");
        panelCantante.add(lblNombreCrearPersona7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 210, 30));

        lblNombreCrearPersona8.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona8.setText("Num. Sencillos:");
        panelCantante.add(lblNombreCrearPersona8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 190, 30));

        lblNombreCrearPersona9.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona9.setText("Num. Conciertos:");
        panelCantante.add(lblNombreCrearPersona9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 200, 30));

        txtNomArtisticoCantante.setToolTipText("Ingrese el nombre artistico del cantante");
        txtNomArtisticoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomArtisticoCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNomArtisticoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 220, 30));

        txtApellidoCantante.setToolTipText("Ingrese el apellido del cantante");
        txtApellidoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtApellidoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 220, 30));

        txtEdadCantante.setToolTipText("Ingrese le edad del cantante");
        txtEdadCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtEdadCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 220, 30));

        txtNacionalidadCantante.setToolTipText("Ingrese la nacionalidad del cantante");
        txtNacionalidadCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalidadCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNacionalidadCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 220, 30));

        txtGeneroMusicalCantante.setToolTipText("Ingrese el genero musical del cantante");
        txtGeneroMusicalCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroMusicalCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtGeneroMusicalCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 220, 30));

        txtNumSencillosCantante.setToolTipText("Ingrese el numero de sencillos del cantante");
        txtNumSencillosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSencillosCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNumSencillosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 220, 30));

        txtNumConciertosCantante.setToolTipText("Ingrese el numero de conciertos dados por el cantante");
        txtNumConciertosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumConciertosCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNumConciertosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 220, 30));

        txtNumGirasCantante.setToolTipText("Ingrese el numero de giras del cantante");
        txtNumGirasCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumGirasCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtNumGirasCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 220, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Crear Cantante:");
        panelCantante.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 110, 30));

        lblNombreCrearPersona10.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona10.setText("Salario:");
        panelCantante.add(lblNombreCrearPersona10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 120, 30));

        txtSalarioCantante.setToolTipText("Ingrese el nombre de la nueva persona");
        txtSalarioCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioCantanteActionPerformed(evt);
            }
        });
        panelCantante.add(txtSalarioCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 904, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< Upstream, based on origin/master
            .addComponent(panelCantante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
=======
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCantante, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addGap(14, 14, 14))
>>>>>>> d4cbfc7 Merge origin/master
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCantanteActionPerformed
        String codigo = txtCodigoCantante.getText();
        int codiguito = Integer.parseInt(codigo);
        String nombre =txtNombreCantante.getText();
        String apellido =txtApellidoCantante.getText();
        String edad =txtEdadCantante.getText();
        int edadcita = Integer.parseInt(edad);
        String nacionalidad =txtNacionalidadCantante.getText();
        String nombreArtistico =txtNomArtisticoCantante.getText();
        String generoMusical =txtGeneroMusicalCantante.getText();
        String numSencillos =txtNumSencillosCantante.getText();
        int sencillos = Integer.parseInt(numSencillos);
        String numConciertos =txtNumConciertosCantante.getText();
        int conciertos = Integer.parseInt(numConciertos);
        String numGiras =txtNumGirasCantante.getText();
        int giras = Integer.parseInt(numGiras);
        String salario = txtSalarioCantante.getText();
        double salarioCan = Double.parseDouble(salario);


        Cantante cantante = new Cantante();
        cantante.setCodigo(codiguito);
        cantante.setNombre(nombre);
        cantante.setApellido(apellido);
        cantante.setEdad(edadcita);
        cantante.setNacionalidad(nacionalidad);
        cantante.setNombreArtistico(nombreArtistico);
        cantante.setGeneroMusical(generoMusical);
        cantante.setNumeroDeSencillos(sencillos);
        cantante.setNumeroDeConciertos(conciertos);
        cantante.setNumeroDeGiras(giras);
        cantante.setSalario(salarioCan);
        
        
        controladorCantante.registrarCantante(cantante);
        JOptionPane.showMessageDialog(this, "El/La cantante ha sido creado exitosamente !:)");
        
        this.limpiarCampos();

  
    }//GEN-LAST:event_btnAceptarCantanteActionPerformed
    private void limpiarCampos () {
        this.txtCodigoCantante.setText("");
        this.txtNombreCantante.setText("");
        this.txtApellidoCantante.setText("");
        this.txtEdadCantante.setText("");
        this.txtNacionalidadCantante.setText("");
        this.txtGeneroMusicalCantante.setText("");
        this.txtNomArtisticoCantante.setText("");
        this.txtNumSencillosCantante.setText("");
        this.txtNumConciertosCantante.setText("");
        this.txtNumGirasCantante.setText("");
        this.txtSalarioCantante.setText("");
                
    }
    private void btnCancelarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCantanteActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarCantanteActionPerformed

    private void txtCodigoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCantanteActionPerformed

    private void txtNombreCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCantanteActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtNomArtisticoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomArtisticoCantanteActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_txtNomArtisticoCantanteActionPerformed

    private void txtApellidoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCantanteActionPerformed

    private void txtEdadCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadCantanteActionPerformed

    private void txtNacionalidadCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadCantanteActionPerformed

    private void txtGeneroMusicalCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroMusicalCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroMusicalCantanteActionPerformed

    private void txtNumSencillosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSencillosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumSencillosCantanteActionPerformed

    private void txtNumConciertosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumConciertosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumConciertosCantanteActionPerformed

    private void txtNumGirasCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumGirasCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumGirasCantanteActionPerformed

    private void txtSalarioCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioCantanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarCantante;
    private javax.swing.JButton btnCancelarCantante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCantante;
    private javax.swing.JLabel lblFechaNacimientoCrearPersona;
    private javax.swing.JLabel lblNombreCrearPersona;
    private javax.swing.JLabel lblNombreCrearPersona1;
    private javax.swing.JLabel lblNombreCrearPersona10;
    private javax.swing.JLabel lblNombreCrearPersona2;
    private javax.swing.JLabel lblNombreCrearPersona3;
    private javax.swing.JLabel lblNombreCrearPersona4;
    private javax.swing.JLabel lblNombreCrearPersona6;
    private javax.swing.JLabel lblNombreCrearPersona7;
    private javax.swing.JLabel lblNombreCrearPersona8;
    private javax.swing.JLabel lblNombreCrearPersona9;
    private javax.swing.JLabel lblcantantaFondo;
    private javax.swing.JLabel lblicono;
    private javax.swing.JPanel panelCantante;
    private javax.swing.JTextField txtApellidoCantante;
    private javax.swing.JTextField txtCodigoCantante;
    private javax.swing.JTextField txtEdadCantante;
    private javax.swing.JTextField txtGeneroMusicalCantante;
    private javax.swing.JTextField txtNacionalidadCantante;
    private javax.swing.JTextField txtNomArtisticoCantante;
    private javax.swing.JTextField txtNombreCantante;
    private javax.swing.JTextField txtNumConciertosCantante;
    private javax.swing.JTextField txtNumGirasCantante;
    private javax.swing.JTextField txtNumSencillosCantante;
    private javax.swing.JTextField txtSalarioCantante;
    // End of variables declaration//GEN-END:variables
}
