/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cantante;

import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.modelo.Cantante;
import javax.swing.JOptionPane;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaBuscarCantantePorDisco extends javax.swing.JInternalFrame {

    private ControladorCantante controladorCantante;

    /**
     * Creates new form VentanaBuscarCantantePorDisco
     */
    public VentanaBuscarCantantePorDisco(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblFechaNacimientoCrearPersona = new javax.swing.JLabel();
        lblNombreCrearPersona = new javax.swing.JLabel();
        txtCodigoDisco = new javax.swing.JTextField();
        txtNombreCantante = new javax.swing.JTextField();
        btnBuscarPorDiscoCantante = new javax.swing.JButton();
        btnCancelarBuscarCantantePorDisco = new javax.swing.JButton();
        lblcantantaFondo = new javax.swing.JLabel();
        lblicono = new javax.swing.JLabel();
        lblCantante = new javax.swing.JLabel();
        lblNombreBuscarCantantePorDisco = new javax.swing.JLabel();
        lblCodigoDiscoBuscarCantante = new javax.swing.JLabel();
        lblNombreCrearPersona3 = new javax.swing.JLabel();
        lblNombreCrearPersona4 = new javax.swing.JLabel();
        lblNombreCrearPersona6 = new javax.swing.JLabel();
        lblNombreCrearPersona7 = new javax.swing.JLabel();
        lblNombreCrearPersona8 = new javax.swing.JLabel();
        lblNombreCrearPersona9 = new javax.swing.JLabel();
        txtNomArtisticoCantante = new javax.swing.JTextField();
        txtApellidoCantante = new javax.swing.JTextField();
        txtEdadCantante = new javax.swing.JTextField();
        txtNacionalidadCantante = new javax.swing.JTextField();
        txtGeneroMusicalCantante = new javax.swing.JTextField();
        txtNumSencillosCantante = new javax.swing.JTextField();
        txtNumConciertosCantante = new javax.swing.JTextField();
        txtNumGirasCantante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblNombreCrearPersona10 = new javax.swing.JLabel();
        txtSalarioCantante = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        lblCodigoCantante = new javax.swing.JLabel();
        txtCodigoCantante = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Buscar Cantante Por Codigo de Disco"));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaNacimientoCrearPersona.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblFechaNacimientoCrearPersona.setText("Apellido:");
        jPanel2.add(lblFechaNacimientoCrearPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 30));

        lblNombreCrearPersona.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona.setText("Num. Giras:");
        jPanel2.add(lblNombreCrearPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 180, 30));

        txtCodigoDisco.setToolTipText("Ingrese el codigo del cantante");
        txtCodigoDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDiscoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigoDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 220, 30));

        txtNombreCantante.setToolTipText("Ingrese el nombre del cantante");
        txtNombreCantante.setEnabled(false);
        txtNombreCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 220, 30));

        btnBuscarPorDiscoCantante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBuscarPorDiscoCantante.setText("Buscar");
        btnBuscarPorDiscoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorDiscoCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarPorDiscoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 106, 32));

        btnCancelarBuscarCantantePorDisco.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelarBuscarCantantePorDisco.setText("Cancelar");
        btnCancelarBuscarCantantePorDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBuscarCantantePorDiscoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelarBuscarCantantePorDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 104, 32));

        lblcantantaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/silue h.png"))); // NOI18N
        jPanel2.add(lblcantantaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 290, 540));

        lblicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpeg"))); // NOI18N
        jPanel2.add(lblicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 360, 700));

        lblCantante.setFont(new java.awt.Font("AkayaTelivigala", 1, 36)); // NOI18N
        lblCantante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1-3.png"))); // NOI18N
        lblCantante.setText("UPS Musik");
        lblCantante.setPreferredSize(new java.awt.Dimension(200, 400));
        jPanel2.add(lblCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 330, 50));

        lblNombreBuscarCantantePorDisco.setFont(new java.awt.Font("AkayaTelivigala", 0, 24)); // NOI18N
        lblNombreBuscarCantantePorDisco.setText("Nombre:");
        jPanel2.add(lblNombreBuscarCantantePorDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 30));

        lblCodigoDiscoBuscarCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblCodigoDiscoBuscarCantante.setText("Codigo Disco:");
        jPanel2.add(lblCodigoDiscoBuscarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, 30));

        lblNombreCrearPersona3.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona3.setText("Edad:");
        jPanel2.add(lblNombreCrearPersona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 78, 30));

        lblNombreCrearPersona4.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona4.setText("Nacionalidad:");
        jPanel2.add(lblNombreCrearPersona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, 30));

        lblNombreCrearPersona6.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona6.setText("Nombre Artistico:");
        jPanel2.add(lblNombreCrearPersona6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 170, 30));

        lblNombreCrearPersona7.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona7.setText("Genero Musical:");
        jPanel2.add(lblNombreCrearPersona7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 160, 30));

        lblNombreCrearPersona8.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona8.setText("Num. Sencillos:");
        jPanel2.add(lblNombreCrearPersona8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 160, 30));

        lblNombreCrearPersona9.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona9.setText("Num. Conciertos:");
        jPanel2.add(lblNombreCrearPersona9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 180, 30));

        txtNomArtisticoCantante.setToolTipText("Ingrese el nombre artistico del cantante");
        txtNomArtisticoCantante.setEnabled(false);
        txtNomArtisticoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomArtisticoCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNomArtisticoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 220, 30));

        txtApellidoCantante.setToolTipText("Ingrese el apellido del cantante");
        txtApellidoCantante.setEnabled(false);
        txtApellidoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellidoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 220, 30));

        txtEdadCantante.setToolTipText("Ingrese le edad del cantante");
        txtEdadCantante.setEnabled(false);
        txtEdadCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtEdadCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 220, 30));

        txtNacionalidadCantante.setToolTipText("Ingrese la nacionalidad del cantante");
        txtNacionalidadCantante.setEnabled(false);
        txtNacionalidadCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalidadCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNacionalidadCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 220, 30));

        txtGeneroMusicalCantante.setToolTipText("Ingrese el genero musical del cantante");
        txtGeneroMusicalCantante.setEnabled(false);
        txtGeneroMusicalCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroMusicalCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtGeneroMusicalCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 220, 30));

        txtNumSencillosCantante.setToolTipText("Ingrese el numero de sencillos del cantante");
        txtNumSencillosCantante.setEnabled(false);
        txtNumSencillosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSencillosCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumSencillosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 220, 30));

        txtNumConciertosCantante.setToolTipText("Ingrese el numero de conciertos dados por el cantante");
        txtNumConciertosCantante.setEnabled(false);
        txtNumConciertosCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumConciertosCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumConciertosCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 220, 30));

        txtNumGirasCantante.setToolTipText("Ingrese el numero de giras del cantante");
        txtNumGirasCantante.setEnabled(false);
        txtNumGirasCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumGirasCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumGirasCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 220, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Buscar cantante por el codigo de un disco:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 300, 30));

        lblNombreCrearPersona10.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblNombreCrearPersona10.setText("Salario:");
        jPanel2.add(lblNombreCrearPersona10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 120, 30));

        txtSalarioCantante.setToolTipText("Ingrese el nombre de la nueva persona");
        txtSalarioCantante.setEnabled(false);
        txtSalarioCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtSalarioCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 220, 30));

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblCodigoCantante.setFont(new java.awt.Font("AkayaKanadaka", 0, 24)); // NOI18N
        lblCodigoCantante.setText("Codigo Cantante:");
        jPanel2.add(lblCodigoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, 30));

        txtCodigoCantante.setToolTipText("Ingrese el codigo del cantante");
        txtCodigoCantante.setEnabled(false);
        txtCodigoCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCantanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigoCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDiscoActionPerformed

    private void txtNombreCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCantanteActionPerformed

    private void btnBuscarPorDiscoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorDiscoCantanteActionPerformed
        String codigo = txtCodigoDisco.getText();
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El codigo del disco del cantante a buscar no ha sido ingresado!");
        } else {
            int codiguito = Integer.parseInt(codigo);
            Cantante cantante = controladorCantante.verCantantexDisco(codiguito);
            if (cantante != null) {
                String codigoCan = String.valueOf(cantante.getCodigo());
                txtCodigoCantante.setText(codigoCan);
                txtNombreCantante.setText(cantante.getNombre());
                txtApellidoCantante.setText(cantante.getApellido());
                String edad = String.valueOf(cantante.getEdad());
                txtEdadCantante.setText(edad);
                txtNacionalidadCantante.setText(cantante.getNacionalidad());
                txtNomArtisticoCantante.setText(cantante.getNombreArtistico());
                txtGeneroMusicalCantante.setText(cantante.getGeneroMusical());
                String numSencillos = String.valueOf(cantante.getNumeroDeSencillos());
                txtNumSencillosCantante.setText(numSencillos);
                String numConciertos = String.valueOf(cantante.getNumeroDeConciertos());
                txtNumConciertosCantante.setText(numConciertos);
                String numGiras = String.valueOf(cantante.getNumeroDeGiras());
                txtNumGirasCantante.setText(numGiras);
                String salarioCan = String.valueOf(cantante.getSalario());
                txtSalarioCantante.setText(salarioCan);
                JOptionPane.showMessageDialog(this, "El/La cantante con disco de codigo " + codiguito + "ha sido encontrado  exitosamente1:)");

            } else {
                JOptionPane.showMessageDialog(this, "El/La cantante con disco de codigo " + codiguito + " no ha sido encontrada !:(");

                this.limpiarCampos();
            }
        }
    }//GEN-LAST:event_btnBuscarPorDiscoCantanteActionPerformed

    private void btnCancelarBuscarCantantePorDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBuscarCantantePorDiscoActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarBuscarCantantePorDiscoActionPerformed

    private void txtNomArtisticoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomArtisticoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomArtisticoCantanteActionPerformed

    private void txtApellidoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCantanteActionPerformed

    private void txtEdadCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadCantanteActionPerformed

    private void txtNacionalidadCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadCantanteActionPerformed

    private void txtGeneroMusicalCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroMusicalCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroMusicalCantanteActionPerformed

    private void txtNumSencillosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSencillosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumSencillosCantanteActionPerformed

    private void txtNumConciertosCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumConciertosCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumConciertosCantanteActionPerformed

    private void txtNumGirasCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumGirasCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumGirasCantanteActionPerformed

    private void txtSalarioCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioCantanteActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtCodigoCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCantanteActionPerformed
    private void limpiarCampos() {
        this.txtCodigoCantante.setText("");
        this.txtNombreCantante.setText("");
        this.txtApellidoCantante.setText("");
        this.txtEdadCantante.setText("");
        this.txtNacionalidadCantante.setText("");
        this.txtGeneroMusicalCantante.setText("");
        this.txtNomArtisticoCantante.setText("");
        this.txtNumSencillosCantante.setText("");
        this.txtNumConciertosCantante.setText("");
        this.txtNumGirasCantante.setText("");
        this.txtSalarioCantante.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPorDiscoCantante;
    private javax.swing.JButton btnCancelarBuscarCantantePorDisco;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCantante;
    private javax.swing.JLabel lblCodigoCantante;
    private javax.swing.JLabel lblCodigoDiscoBuscarCantante;
    private javax.swing.JLabel lblFechaNacimientoCrearPersona;
    private javax.swing.JLabel lblNombreBuscarCantantePorDisco;
    private javax.swing.JLabel lblNombreCrearPersona;
    private javax.swing.JLabel lblNombreCrearPersona10;
    private javax.swing.JLabel lblNombreCrearPersona3;
    private javax.swing.JLabel lblNombreCrearPersona4;
    private javax.swing.JLabel lblNombreCrearPersona6;
    private javax.swing.JLabel lblNombreCrearPersona7;
    private javax.swing.JLabel lblNombreCrearPersona8;
    private javax.swing.JLabel lblNombreCrearPersona9;
    private javax.swing.JLabel lblcantantaFondo;
    private javax.swing.JLabel lblicono;
    private javax.swing.JTextField txtApellidoCantante;
    private javax.swing.JTextField txtCodigoCantante;
    private javax.swing.JTextField txtCodigoDisco;
    private javax.swing.JTextField txtEdadCantante;
    private javax.swing.JTextField txtGeneroMusicalCantante;
    private javax.swing.JTextField txtNacionalidadCantante;
    private javax.swing.JTextField txtNomArtisticoCantante;
    private javax.swing.JTextField txtNombreCantante;
    private javax.swing.JTextField txtNumConciertosCantante;
    private javax.swing.JTextField txtNumGirasCantante;
    private javax.swing.JTextField txtNumSencillosCantante;
    private javax.swing.JTextField txtSalarioCantante;
    // End of variables declaration//GEN-END:variables
}
