/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */

package ec.edu.ups.practica_05_ssuquilanda_jabad.main;

<<<<<<< Upstream, based on origin/master
=======


>>>>>>> d4cbfc7 Merge origin/master
import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.controlador.ControladorCompositor;
import ec.edu.ups.practica_05_ssuquilanda_jabad.dao.CantanteDAO;
import ec.edu.ups.practica_05_ssuquilanda_jabad.dao.CompositorDAO;
import ec.edu.ups.practica_05_ssuquilanda_jabad.idao.ICantanteDAO;
import ec.edu.ups.practica_05_ssuquilanda_jabad.idao.ICompositorDAO;
<<<<<<< Upstream, based on origin/master
import ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cantante.VentanaBuscarCantante;
import ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cantante.VentanaBuscarCantantePorDisco;
=======
>>>>>>> d4cbfc7 Merge origin/master
import ec.edu.ups.practica_05_ssuquilanda_jabad.vista.cantante.VentanaCrearCantante;

/**
 *
 * @author samanthasuquilandaquilli
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    //Ventanas Cantante
    private VentanaCrearCantante ventanaCrearCantante;
<<<<<<< Upstream, based on origin/master
    private VentanaBuscarCantante ventanaBuscarCantante;
    private VentanaBuscarCantantePorDisco ventanaBuscarCantantePorDisco;
    private VentanaActualizarPersona ventanaActualizarPersona;
    private VentanaEliminarPersona ventanaEliminarPersona;
    private VentanaListarPersona ventanaListarPersona;
=======
    //private VentanaBuscarPersona ventanaBuscarPersona;
    //private VentanaActualizarPersona ventanaActualizarPersona;
    //private VentanaEliminarPersona ventanaEliminarPersona;
    //private VentanaListarPersona ventanaListarPersona;
>>>>>>> d4cbfc7 Merge origin/master
    //Ventanas Compositor
    //private VentanaCrearOperadoraTelefonica ventanaCrearOperadoraTelefonica;
    //private VentanaBuscarOperadoraTelefonica ventanaBuscarOperadoraTelefonica;
    //private VentanaActualizarOperadoraTelefonica ventanaActualizarOperadoraTelefonica;
    //private VentanaEliminarOperadoraTelefonica ventanaEliminarOperadoraTelefonica;
    //private VentanaListarOperadoraTelefonica ventanaListarOperadoraTelefonica;
    
    
    //Controladores
    private ControladorCantante controladorCantante;
    private ControladorCompositor compositorControlador;
    //DAO´s
    private ICompositorDAO compositorDAO;
    
    private ICantanteDAO cantanteDAO;
    
    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() {
        initComponents();
        compositorDAO = new CompositorDAO();
        cantanteDAO = new CantanteDAO();
        controladorCantante = new ControladorCantante(cantanteDAO);
        compositorControlador = new ControladorCompositor(compositorDAO);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblFondoPrincipal = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        CantanteMenu = new javax.swing.JMenu();
        menuItemCrearCantante = new javax.swing.JMenuItem();
        menuItemBuscarCantante = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuItemActualizarPersona = new javax.swing.JMenuItem();
        menuItemEliminarPersona = new javax.swing.JMenuItem();
        menuItemListarPersona = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuOpciones = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/practica_05_ssuquilanda_jabad/main/icon.png"))); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(190, 70, 470, 390);

        lblFondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/practica_05_ssuquilanda_jabad/main/fondo.jpeg"))); // NOI18N
        desktopPane.add(lblFondoPrincipal);
        lblFondoPrincipal.setBounds(0, 0, 0, 520);

        CantanteMenu.setMnemonic('f');
        CantanteMenu.setText("Cantante");
        CantanteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantanteMenuActionPerformed(evt);
            }
        });

        menuItemCrearCantante.setMnemonic('o');
        menuItemCrearCantante.setText("Crear");
        menuItemCrearCantante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuItemCrearCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearCantanteActionPerformed(evt);
            }
        });
        CantanteMenu.add(menuItemCrearCantante);

        menuItemBuscarCantante.setMnemonic('a');
        menuItemBuscarCantante.setText("Buscar");
        menuItemBuscarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarCantanteActionPerformed(evt);
            }
        });
        CantanteMenu.add(menuItemBuscarCantante);

        jMenuItem2.setText("Buscar Cantante Por Disco");
        CantanteMenu.add(jMenuItem2);

        menuItemActualizarPersona.setMnemonic('s');
        menuItemActualizarPersona.setText("Actualizar");
        menuItemActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarPersonaActionPerformed(evt);
            }
        });
        CantanteMenu.add(menuItemActualizarPersona);

        menuItemEliminarPersona.setMnemonic('x');
        menuItemEliminarPersona.setText("Eliminar");
        menuItemEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarPersonaActionPerformed(evt);
            }
        });
        CantanteMenu.add(menuItemEliminarPersona);

        menuItemListarPersona.setText("Listar");
        menuItemListarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarPersonaActionPerformed(evt);
            }
        });
        CantanteMenu.add(menuItemListarPersona);

        jMenuItem3.setText("Crear Disco");
        CantanteMenu.add(jMenuItem3);

        menuBar.add(CantanteMenu);

        menuOpciones.setText("Opciones");
        menuOpciones.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuOpcionesMenuSelected(evt);
            }
        });

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuOpciones.add(menuItemSalir);

        menuBar.add(menuOpciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemBuscarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarCantanteActionPerformed
        if(ventanaBuscarCantante == null){
            ventanaBuscarCantante = new VentanaBuscarCantante(controladorCantante);
            desktopPane.add(ventanaBuscarCantante);
        }
        ventanaBuscarCantante.setVisible(true);
    }//GEN-LAST:event_menuItemBuscarCantanteActionPerformed

    private void menuOpcionesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuOpcionesMenuSelected
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuOpcionesMenuSelected

    private void menuItemListarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarPersonaActionPerformed
        if(ventanaListarPersona == null){
            ventanaListarPersona = new VentanaListarPersona(personaControlador);
            desktopPane.add(ventanaListarPersona);
        }
        ventanaListarPersona.setVisible(true);
    }//GEN-LAST:event_menuItemListarPersonaActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemCrearCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearCantanteActionPerformed
        if (ventanaCrearCantante == null){
            ventanaCrearCantante = new VentanaCrearCantante(controladorCantante);
            desktopPane.add(ventanaCrearCantante);
        }
       
        ventanaCrearCantante.setVisible(true);
        
    }//GEN-LAST:event_menuItemCrearCantanteActionPerformed

    private void menuItemActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarPersonaActionPerformed
        if (ventanaActualizarPersona == null){
            ventanaActualizarPersona=new VentanaActualizarPersona(personaControlador);
            desktopPane.add(ventanaActualizarPersona);
        }
       
        ventanaActualizarPersona.setVisible(true);
    }//GEN-LAST:event_menuItemActualizarPersonaActionPerformed

    private void menuItemEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarPersonaActionPerformed
        if (ventanaEliminarPersona == null){
            ventanaEliminarPersona=new VentanaEliminarPersona(personaControlador);
            desktopPane.add(ventanaEliminarPersona);
        }
       
        ventanaEliminarPersona.setVisible(true);
    }//GEN-LAST:event_menuItemEliminarPersonaActionPerformed

    private void CantanteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantanteMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantanteMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CantanteMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblFondoPrincipal;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemActualizarPersona;
    private javax.swing.JMenuItem menuItemBuscarCantante;
    private javax.swing.JMenuItem menuItemCrearCantante;
    private javax.swing.JMenuItem menuItemEliminarPersona;
    private javax.swing.JMenuItem menuItemListarPersona;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuOpciones;
    // End of variables declaration//GEN-END:variables

}
